### ISSUE TITLE
Can BEERS2 use molecule packets from CAMAPREE?

### ISSUE THREAD

**Issue by isaacvock** [itmat/BEERS2#5]
Hello,

First off, thank you all for developing amazing, ultra-sophisticated RNA-seq simulators for the field. I am very excited to make extensive use of CAMPAREE and BEERS2.

I was able to successfully install CAMPAREE and BEERS2, run CAMPAREE, and configure BEERS2. When I ran CAMPAREE, I set the `output['type']` parameter to `packet`, as the documentation said it would be "suitable for use by the BEERS2 simulator". When I ran BEERS2 though, with `library_prep_pipeline['input]['directory_path']` set to the directory containing the sample1 directory holding the simulated molecules from CAMPAREE, the pipeline ran (in a couple seconds), but generated entirely empty simulated fastq files. The printed output also indicated that no molecule files were found. Judging by the Snakefile, this is because

```
def input_molecule_files(sample):
    directory = config["library_prep_pipeline"]["input"].get("directory_path", None)

    if directory is None:
        return []

    molecule_files_directory = Path(f"{directory}/sample{sample}")
    molecule_files = sorted(molecule_files_directory.glob("molecule_*.txt"))

    print(f"Molecule files for sample {sample}:", molecule_files)
    return molecule_files
```

specifically looks for .txt molecule files (which I assume is the output if I had set `type` to `file`). Is there a way to get it to accept the pickled binary files from CAMPAREE as input instead?

Best,
Isaac

**Comment by tgbrooks** [comment]
Hi Isaac,

Thanks for reaching out! We apologize for that oversight. We later added a different way to run CAMPAREE and BEERS where BEERS actually generates the molecule packets using the rest of CAMPAREE's output, so loading the pickle files got sidelined unintentionally. I've just added back support for that and pushed it to github, so if you update BEERS you should be able to use the pickle files (hopefully) with exactly what you've been trying.

Alternatively, you can run it where BEERS generates the actual molecule packets by using the `from_distribution_data` section of the config file. This should work on your current install of BEERS.

Let me know if you have any trouble with either of those, or anything else.

Best,
Tom

**Comment by isaacvock** [comment]
Hi Tom,

Thank you very much for implementing a patch so rapidly; looks like it is working like a charm!

Best,
Isaac
