### ISSUE TITLE
Unexpected CIGAR strings

### ISSUE THREAD

**Issue by marzie-rasekh** [itmat/BEERS2#6]
In the simulated bam files provided from your article, we notice strange CIGAR strings. Such as: 
```
BEERS:1:1:1909:22846:29830:1_ENSMUST00000192692_1.124232.1355753.cdna.cdna.3    163     1       3647309 255     21S2I56S21M     *       0       0       TTTTTTTTTTTTTTTTTTTTTCCTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTGGTTTTGGGTTTTTGCTGAAG JJEJJJJJJJJJJJJJJJJJJJJJJJJJJ;5JJ8J>JJGAJJDJ<FJCJFGJJJJJJJJIJJAJJJIB.9FJ/:J4JJ:97:I=69.IJJ2IFJJ?7C>, 

BEERS:1:1:2212:26005:35385:1_ENSMUST00000188299_1.156517.1687287.cdna.cdna.8    163     1       24612775        255     1I99S   *       0       0       ATTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTATTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT     [JJJJJJJJJJJJJJJJJJJJJ?JJJJJJJJJ@JJ;JJJJAJJJ4JJ?JJJJJ@G;JJJIJ@JEJJHJ$JJGF3<JJ5G9J1H.<#AJ/GB8HJ/JJ+B<9](mailto:JJJJJJJJJJJJJJJJJJJJJ?JJJJJJJJJ@JJ;JJJJAJJJ4JJ?JJJJJ@G;JJJIJ@JEJJHJ$JJGF3%3cJJ5G9J1H.%3c%23AJ/GB8HJ/JJ+B%3C9)
```

I was wondering if you could guide us on how to interpret such CIGAR strings.

**Comment by tgbrooks** [comment]
Hi, thank you for reaching out.

Both of these represent reads that are primarily polyA tails, which are added post-transcriptionally and so have no true way to align to the genome. Nonetheless, BEERS2 is aware of where these reads came from, which originally included an actual transcript (with polyA tail), and tracks the origin of the read via its CIGAR string.

The bases coming from the polyA tail show in the CIGAR string as "S" entries. There are also some insertions during sequencing (e.g., PCR) that show as "I" entries. Both of these would be impossible for an actual sequencer to align given that the polyA tail does not originate from a genomic location (unless the 21 non-polyA tail bases in the first read were enough to align).

How to make use of this information depends upon your use case. For example, evaluating an aligner should probably be done by either filtering out reads like this (as no aligner has any hope of succeeding) or by looking only at 'genomic' bases, which have an "M" entry in the CIGAR string and do have an actual genomic location. In particular, I would say that non-alignment of a read perfectly matches any read whose CIGAR string is completely comprised of I/S entries. (For reference, see the table on page 8 of the [SAM documentation](https://samtools.github.io/hts-specs/SAMv1.pdf) which documents the meaning of each CIGAR entry in a nice way.)

Lastly, note that under some configurations, BEERS2 produces a lot more polyA tail sequence than seen in real data. Hence, you'll see an aberrant number of reads like this if using these settings. More realistic levels of polyA tail are obtained when including the more realistic biases (GC content and hexamer priming sequence biases), which naturally reduce the number of these molecules that end up being sequenced. You can see the config files used in our paper [here](http://bioinf.itmat.upenn.edu/BEERS2/paper/index.html) for reference - the All Bias one for example has much less polyA tails in reads and we believe is the most realistic.

Please let me know if that didn't answer the question.

**Comment by marzie-rasekh** [comment]
Thank you. This answers our question. We will remove them in our analysis.
